analyzer:
  exclude:
    - build/**
    - .dart_tool/**

linter:
  rules:
    always_declare_return_types: true
    annotate_overrides: true
    avoid_dynamic_calls: true
    avoid_empty_else: true
    avoid_print: true
    cancel_subscriptions: true
    directives_ordering: true
    prefer_const_constructors: true
    prefer_final_locals: true
    prefer_single_quotes: true
    sort_child_properties_last: true
